### PR TITLE
Caller notes API changes

### PR DESCRIPTION
**Pull request by asokoloski**
Commit messages should explain everything, but let me know if you want more details... or if there's a reason to keep grandcanyon.iml in version control that I haven't thought of :)

This change should be safe to release as is (assuming I haven't broken anything!), and then the admin site changes can follow.

### CODE REVIEW

**Review by boralben — APPROVED** [review]

**Comment by boralben** [comment]
💯  confirmed notes are able to get retrieved and updated.

**Comment by asokoloski** [comment]
@boralben Thank you!  Is the process typically that the MR author merges after the review / approval?

**Comment by boralben** [comment]
I'll leave them to you to merge

**Comment by asokoloski** [comment]
Ok, thanks!

**Pull request merged**
