### PR TITLE
Streamline database container management

### PR DESCRIPTION
**Pull request by asokoloski**
Create command for initializing Mysql DB Docker container from
scratch, as well as commands to start up / shut down / destroy it.

Also create command to automate the previous method of initializing
the database (using newman), but now only for the purpose of re-generating
the dummy data.

@boralben  What do you think of this change?  I remember you mentioning that this was the direction you wanted to go with the db setup.  I didn't want to completely discard the newman stuff -- I think there's value in exercising the API that way, to make sure that everything works, and to ensure that the dummy database SQL seed can easily stay in sync with the way the code actually writes to the database.

I know this is not directly related to the comment field for callers task I'm assigned, I plan to dig into that next.  I just wanted to first make it easier to completely discard and re-create the database, which I've found to be a good foundation on which to build automated tests.  It should also help any new developers get set up more quickly (I hope!)

The `./run.sh regenerate-dummy-data` command is a bit held together with duct tape and twine, but it seems to work :) 
Thanks!
Aaron

### CODE REVIEW

**Comment by boralben** [comment]
Thanks very much, @asokoloski. This is terrific! I have a question about 3306 vs 3316. What's behind that?

**Comment by boralben** [comment]
Oh, and also wanted to mention that this works flawlessly on my machine

**Comment by asokoloski** [comment]
@boralben 3316 is just an arbitrary port that's not 3306 so it doesn't clash with an existing running db container.  I know there's a warning in there about shutting down your normal db container, so technically that's not actually necessary now.   End goal is to make it completely isolated -- if we can make the frontend start serving http on a different port and make newman connect to that port instead, you'll be able to run the command despite everything else running for your dev environment.  But it's good enough as it is for now, I think.

**Review by boralben — APPROVED** [review]

**Comment by asokoloski** [comment]
Thanks!

**Pull request merged**
